//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.10.26 at 02:11:54 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eurotech.com/esf/2.0", xmlns = {
                                                                                          @XmlNs(namespaceURI = "http://eurotech.com/esf/2.0", prefix = "esf"),
                                                                                          @XmlNs(namespaceURI = "http://www.osgi.org/xmlns/metatype/v1.2.0", prefix = "ocd")
}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED)
package org.eclipse.kapua.service.device.call.kura.model.configuration;

import javax.xml.bind.annotation.XmlNs;
