#!/bin/sh
################################################################################
#    Copyright (c) 2017, 2018 Red Hat Inc and others
#   
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#   
#    Contributors:
#        Red Hat Inc - initial API and implementation
#        Eurotech
################################################################################

# Check for Keycloak integration
if [ -n "$KEYCLOAK_URL" ] && [ -n "$KAPUA_URL" ]; then
   echo "Activating Keycloak integration..."
   echo "  Keycloak: $KEYCLOAK_URL"
   echo "  Kapua:    $KAPUA_URL"
   
   : KEYCLOAK_REALM=${KEYCLOAK_REALM:=kapua}
   : KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:=console}
   
   JAVA_OPTS="$JAVA_OPTS -Dsso.provider=keycloak"
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.client.id=${KEYCLOAK_CLIENT_ID}"
   
   test -n "$KEYCLOAK_CLIENT_SECRET" && JAVA_OPTS="$JAVA_OPTS -Dsso.openid.client.secret=${KEYCLOAK_CLIENT_SECRET}"
   
   JAVA_OPTS="$JAVA_OPTS -Dsso.keycloak.uri=${KEYCLOAK_URL}"
   JAVA_OPTS="$JAVA_OPTS -Dsso.keycloak.realm=${KEYCLOAK_REALM}"
   JAVA_OPTS="$JAVA_OPTS -Dauthentication.credential.jwt.issuer.allowed=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}"
   
   JAVA_OPTS="$JAVA_OPTS -Dsite.home.uri=${KAPUA_URL}"
   
   export JAVA_OPTS
fi

# Continue with startup
exec /var/opt/jetty/run-jetty "$@"
