#!/bin/sh

################################################################################
#    Copyright (c) 2017 Red Hat Inc
#   
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#   
#    Contributors:
#        Red Hat Inc - initial API and implementation
################################################################################

# Generate X509 certificate and private key
openssl req -x509 -newkey rsa:4096 -keyout /var/opt/jetty/key.pem -out /var/opt/jetty/cert.pem -days 365 -nodes -subj '/O=Eclipse Kapua/C=XX'
openssl pkcs8 -topk8 -in /var/opt/jetty/key.pem -out /var/opt/jetty/key.pk8 -nocrypt
rm /var/opt/jetty/key.pem

START_ARGS="$START_ARGS -Djetty.home=/opt/jetty"
START_ARGS="$START_ARGS -Djetty.base=/var/opt/jetty"

# START_ARGS : Arguments to the starter JVM
# JAVA_OPTS : Arguments to the server JVMs

eval echo "START_ARGS = $START_ARGS"
eval echo "JAVA_OPTS = $JAVA_OPTS"
eval exec /usr/bin/java $START_ARGS -jar /opt/jetty/start.jar $JAVA_OPTS "$@"
