#!/bin/sh

################################################################################
#    Copyright (c) 2017, 2018 Eurotech
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
################################################################################

# Configure credentials

: ARTEMIS_USER=${ARTEMIS_USER:=kapua-sys}
: ARTEMIS_PASS=${ARTEMIS_PASS:=kapua-password}

sh
#/opt/artemis/bin/artemis user add --user ${ARTEMIS_USER} --password ${ARTEMIS_PASS} --role amq

# Continue with startup
cd /opt/artemis/

/opt/artemis/bin/artemis create \
    --allow-anonymous \
    --aio \
    --autocreate \
    --cluster-password password \
    --cluster-user user \
    --data ./data/kapua \
    --default-port 1883 \
    --home /opt/artemis \
    --host ${BINDING_IP:-0.0.0.0} \
    --name kapua \
    --password password \
    --user user \
    --verbose kapua

echo 'copying configuration...'
cp /opt/artemis/base-configuration/* /opt/artemis/kapua/etc
echo 'copying configuration... DONE'

echo 'copying libraries...'
cp /opt/artemis/base-lib/* /opt/artemis/kapua/lib
echo 'copying libraries... DONE'

echo 'copying bin...'
cp /opt/artemis/script/* /opt/artemis/kapua/bin/artemis
echo 'copying bin... DONE'

echo 'starting Artemis...'
/opt/artemis/kapua/bin/artemis run xml:/opt/artemis/kapua/etc/bootstrap.xml