#!/bin/sh

# Generate X509 certificate and private key
openssl req -x509 -newkey rsa:4096 -keyout /home/kapua/key.pem -out /home/kapua/cert.pem -days 365 -nodes -subj '/O=Eclipse Kapua/C=XX'
openssl pkcs8 -topk8 -in /home/kapua/key.pem -out /home/kapua/key.pk8 -nocrypt
rm /home/kapua/key.pem

# Run broker
/maven/bin/activemq console
