#!/bin/sh

################################################################################
#    Copyright (c) 2017, 2018 Eurotech
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
################################################################################

# Configure credentials

: ARTEMIS_USER=${ARTEMIS_USER:=kapua-sys}
: ARTEMIS_PASS=${ARTEMIS_PASS:=kapua-password}

/opt/artemis/bin/artemis user add --user ${ARTEMIS_USER} --password ${ARTEMIS_PASS} --role amq

# Continue with startup

exec /opt/artemis/bin/artemis run xml:${ARTEMIS_CONFIGURATION}/bootstrap.xml
