#!/bin/sh

################################################################################
#    Copyright (c) 2017, 2022 Eurotech
#
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#    SPDX-License-Identifier: EPL-2.0
#
################################################################################

# Configure credentials

: ARTEMIS_USER=${ARTEMIS_USER:=kapua-sys}
: ARTEMIS_PASS=${ARTEMIS_PASS:=kapua-password}

/opt/artemis/bin/artemis user add --user ${ARTEMIS_USER} --password ${ARTEMIS_PASS} --role amq

# Continue with startup

exec /opt/artemis/bin/artemis run xml:${ARTEMIS_CONFIGURATION}/bootstrap.xml
