#!/bin/sh
################################################################################
#    Copyright (c) 2011, 2018 Eurotech and/or its affiliates and others
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
#    Contributors:
#        Eurotech
################################################################################

# Generate X509 certificate and private key
openssl req -x509 -newkey rsa:4096 -keyout /home/kapua/key.pem -out /home/kapua/cert.pem -days 365 -nodes -subj '/O=Eclipse Kapua/C=XX'
openssl pkcs8 -topk8 -in /home/kapua/key.pem -out /home/kapua/key.pk8 -nocrypt
rm /home/kapua/key.pem

# Run broker
/maven/bin/activemq console
