#!/bin/bash
################################################################################
#    Copyright (c) 2016, 2022 Eurotech and/or its affiliates and others
#
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#    SPDX-License-Identifier: EPL-2.0
#
#    Contributors:
#        Eurotech
################################################################################

ACTIVEMQ_BASE="/var/opt/activemq"

## Certificate Options

: ${KAPUA_DISABLE_SSL:="true"}

if [ "${KAPUA_DISABLE_SSL}" == "false" ]; then

    # Certificates directory configuration
    CERTIFICATES_PATH="tls"

    if [ ! -d "${ACTIVEMQ_BASE}/${CERTIFICATES_PATH}" ]; then
        mkdir -p "${ACTIVEMQ_BASE}/${CERTIFICATES_PATH}"
    fi

    # Keystore configuration
    : ${KEYSTORE_NAME:="kapua.jks"}
    : ${KAPUA_KEYSTORE_PASSWORD:="changeit"}

    if [ ! -f "${ACTIVEMQ_BASE}/${CERTIFICATES_PATH}/${KEYSTORE_NAME}" ]; then
      if [ -z "${KAPUA_KEYSTORE}" ]; then
          if [ -n "${KAPUA_KEY_PASSWORD}" ]; then
              PASSWORD_PARAM="-passin pass:${KAPUA_KEY_PASSWORD}";
          fi
          openssl pkcs12 -export -in <(echo "${KAPUA_CRT}"; echo "${KAPUA_CA}") -inkey <(echo "${KAPUA_KEY}") ${PASSWORD_PARAM} -name kapua -password pass:"${KAPUA_KEYSTORE_PASSWORD}" -out "${ACTIVEMQ_BASE}/${CERTIFICATES_PATH}/${KEYSTORE_NAME}"
      else
          echo "${KAPUA_KEYSTORE}" | base64 --decode > "${ACTIVEMQ_BASE}/${CERTIFICATES_PATH}/${KEYSTORE_NAME}"
      fi
    fi

    ACTIVEMQ_SSL_OPTS="${ACTIVEMQ_SSL_OPTS} -Djavax.net.ssl.keyStore=${ACTIVEMQ_BASE}/${CERTIFICATES_PATH}/${KEYSTORE_NAME}"
    ACTIVEMQ_SSL_OPTS="${ACTIVEMQ_SSL_OPTS} -Djavax.net.ssl.keyStorePassword=${KAPUA_KEYSTORE_PASSWORD}"
    ACTIVEMQ_SSL_OPTS="${ACTIVEMQ_SSL_OPTS} -Djavax.net.ssl.trustStore=${ACTIVEMQ_BASE}/${CERTIFICATES_PATH}/${KEYSTORE_NAME}"
    ACTIVEMQ_SSL_OPTS="${ACTIVEMQ_SSL_OPTS} -Djavax.net.ssl.trustStorePassword=${KAPUA_KEYSTORE_PASSWORD}"

    export ACTIVEMQ_SSL_OPTS
fi

if [ "${KAPUA_DISABLE_DATASTORE:-false}" == "true" ]; then
  sed -i '/BEGIN DATASTORE PERSISTENCE/,/END DATASTORE PERSISTENCE/d' /opt/activemq/conf/camel.xml
  sed -i '/BEGIN DATASTORE PERSISTENCE/,/END DATASTORE PERSISTENCE/d' /opt/activemq/conf/camel-routes.xml
fi

# Run broker
/opt/activemq/bin/activemq console
