openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs Steps
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobs/{jobId}/steps:
    get:
      tags:
        - Job - Step
      summary: Get all the Jobs Steps
      operationId: jobStepList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
        - name: name
          in: query
          description: The job step name to filter results
          schema:
            type: string
        - $ref: '../openapi.yaml#/components/parameters/sortParam'
        - $ref: '../openapi.yaml#/components/parameters/sortDir'
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
        - $ref: '../openapi.yaml#/components/parameters/askTotalCount'
      responses:
        200:
          description: The list of the Steps of the Job
          content:
            application/json:
              schema:
                $ref: './jobStep.yaml#/components/schemas/jobStepListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    post:
      tags:
        - Job - Step
      summary: Create a new Job Step
      operationId: jobStepCreate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
      requestBody:
        description: An object containing the properties for the new Job Step to be created
        content:
          application/json:
            schema:
              $ref: './jobStep.yaml#/components/schemas/jobStepCreator'
        required: true
      responses:
        201:
          description: The Job Step that has just been created
          content:
            application/json:
              schema:
                $ref: './jobStep.yaml#/components/schemas/jobStep'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        409:
          $ref: '../openapi.yaml#/components/responses/entityUniqueness'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
