#!/usr/bin/env bash
###############################################################################
# Copyright (c) 2020, 2022 Eurotech and/or its affiliates and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Eurotech - initial API and implementation
###############################################################################


#
# This deploys the Keycloak image into the Minishift VM.
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OPENSHIFT_SSO_DIR="${SCRIPT_DIR}/../../openshift/sso"
KEYCLOAK_IMAGE="keycloak:sso"

# Build the Keycloak image if missing
if [[ "$(docker images -q ${KEYCLOAK_IMAGE} 2> /dev/null)" == "" ]] ; then
  cd "${SCRIPT_DIR}/../../commons/sso/keycloak/"
  . "./build"
  :
fi

echo "Running Minishift Keycloak Importer script..."
./keycloak-importer ||
    {
        echo "Running Minishift Keycloak Importer script... FAILED!";
        exit 1;
    }
echo "Running Minishift Keycloak Importer script... DONE!"

eval "$(minishift oc-env)"
exec "${OPENSHIFT_SSO_DIR}/deploy"
