#!/usr/bin/env bash
###############################################################################
# Copyright (c) 2020 Eurotech and/or its affiliates and others
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     Eurotech - initial API and implementation
###############################################################################

#
# This script removes the Keycloak image from the Minishift VM.
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OPENSHIFT_SSO_DIR="${SCRIPT_DIR}/../../openshift/sso"

eval "$(minishift oc-env)"
exec "${OPENSHIFT_SSO_DIR}/destroy"
