#!/bin/sh
################################################################################
#    Copyright (c) 2020, 2022 Eurotech and/or its affiliates and others
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
#    Contributors:
#        Eurotech
################################################################################

JAVA_OPTS="${JAVA_OPTS} --add-opens java.base/java.lang=ALL-UNNAMED"

java ${JAVA_OPTS} ${DEBUG_OPTS} ${JMX_OPTS} -jar kapua-consumer-lifecycle-2.1.0-SEC-FIX-SNAPSHOT-app.jar
