#!/bin/sh
################################################################################
#    Copyright (c) 2020 Eurotech and/or its affiliates and others
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
#    Contributors:
#        Eurotech
################################################################################

#remote debugging
#-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8001,suspend=y
#define external variable to enable/disable this

DEBUG_OPTIONS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8001,suspend=n"

java ${JAVA_OPTS} ${DEBUG_OPTIONS} -jar kapua-consumer-lifecycle-1.5.0-CAMEL-SNAPSHOT-uber.jar