#!/usr/bin/env bash
###############################################################################
# Copyright (c) 2020, 2022 Eurotech and/or its affiliates and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Eurotech - initial API and implementation
###############################################################################

echo "Building Kapua Keycloak Docker image..."

docker build -f ./docker/Dockerfile -t kapua/kapua-keycloak:"${IMAGE_VERSION:=2.1.0-SEC-FIX-SNAPSHOT}" . ||
{
    echo "Building Kapua Keycloak docker image... ERROR!"
    exit 1
}

echo "Building Kapua Keycloak docker image... DONE!"