openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Roles
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/roles:
    get:
      tags:
        - Role
      summary: Get all the roles
      operationId: roleList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - name: name
          in: query
          description: The role name to filter results
          schema:
            type: string
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
      responses:
        200:
          description: The list of the Roles available in the Scope
          content:
            application/json:
              schema:
                $ref: './role.yaml#/components/schemas/roleListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    post:
      tags:
        - Role
      summary: Create a new Role
      operationId: roleCreate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        description: An object containing the properties for the new Role to be created
        content:
          application/json:
            schema:
              $ref: './role.yaml#/components/schemas/roleCreator'
        required: true
      responses:
        200:
          description: The Role that has just been created
          content:
            application/json:
              schema:
                $ref: './role.yaml#/components/schemas/role'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
