openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Bundle
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/bundles/_stop:
    post:
      tags:
        - Device Management - Bundle
      summary: Stop the desired Bundle on a single Device
      operationId: deviceBundleStop
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: './deviceBundle.yaml#/components/parameters/bundleId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      responses:
        200:
          description: The Bundle has been successfully stopped
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
