<?xml version="1.0"?>
<!--
    Copyright (c) 2017, 2022 Red Hat Inc and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
        Red Hat Inc - initial API and implementation
        Eurotech
 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kapua</groupId>
        <artifactId>kapua</artifactId>
        <version>2.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>kapua-assembly</artifactId>
    <name>${project.artifactId}</name>
    <packaging>pom</packaging>

    <properties>
        <docker.account>eclipsekapua</docker.account>
        <docker.image.name>image-name</docker.image.name>
        <docker.push.skip.latest>true</docker.push.skip.latest>
    </properties>

    <modules>
        <module>java-base</module>
        <module>jetty-base</module>
        <module>sql</module>

        <module>events-broker</module>

        <module>broker-artemis</module>
        <module>service</module>
        <module>consumer</module>

        <module>api</module>
        <module>job-engine</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.kapua</groupId>
                <artifactId>kapua-assembly-java-base</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>org.apache.activemq</groupId>
                <artifactId>apache-activemq</artifactId>
                <classifier>bin</classifier>
                <type>tar.gz</type>
                <version>${activemq.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <!-- Profile used to exclude console module on release process -->
        <profile>
            <id>console</id>
            <modules>
                <module>console</module>
            </modules>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <configuration>
                    <excludeArtifacts>${project.artifactId}</excludeArtifacts>
                </configuration>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>io.fabric8</groupId>
                    <artifactId>docker-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>Build Docker Container</id>
                            <phase>install</phase>
                            <goals>
                                <goal>build</goal>
                            </goals>
                            <configuration>
                                <images>
                                    <image>
                                        <name>${docker.account}/${docker.image.name}</name>

                                        <build>
                                            <dockerFile>${project.basedir}/docker/Dockerfile</dockerFile>
                                            <filter>@</filter>

                                            <tags>
                                                <tag>${project.version}</tag>
                                            </tags>
                                        </build>
                                    </image>
                                </images>
                            </configuration>
                        </execution>

                        <execution>
                            <id>Push Docker Container</id>
                            <phase>deploy</phase>
                            <goals>
                                <goal>push</goal>
                            </goals>
                            <configuration>
                                <images>
                                    <image>
                                        <name>${docker.account}/${docker.image.name}:latest</name>
                                        <build>
                                            <skipPush>${docker.push.skip.latest}</skipPush>
                                        </build>
                                    </image>
                                    <image>
                                        <name>${docker.account}/${docker.image.name}:${project.version}</name>
                                        <build>
                                            <skipPush>false</skipPush>
                                        </build>
                                    </image>
                                </images>

                                <authConfig>
                                    <username>${env.DOCKER_USERNAME}</username>
                                    <password>${env.DOCKER_TOKEN}</password>
                                </authConfig>
                            </configuration>
                        </execution>

                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
