openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Device Management - Operations
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/operations:
    get:
      tags:
        - Device Management - Operation
      summary: Get all the Device Registry Operations
      operationId: deviceRegistryOperationList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - name: resource
          in: query
          description: The resource of the DeviceManagementOperation in which to search results
          schema:
            type: string
        - $ref: '../deviceOperation/deviceOperation.yaml#/components/parameters/status'
        - $ref: '../openapi.yaml#/components/parameters/askTotalCount'
        - $ref: '../openapi.yaml#/components/parameters/sortParam'
        - name: sortDir
          in: query
          description: The sort direction. Can be ASCENDING (default), DESCENDING. Case-insensitive (except for "clientId" parameter).
          schema:
            type: string
            enum:
              - ASCENDING
              - DESCENDING
            default: ASCENDING
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
      responses:
        200:
          description: The list of the Device Management Registty Operations available in the Scope
          content:
            application/json:
              schema:
                $ref: './deviceOperation.yaml#/components/schemas/deviceOperationListResult'
        400:
          $ref: '../openapi.yaml#/components/responses/illegalArgument'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
