openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Credentials
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/credentials/{credentialId}:
    get:
      tags:
        - Credential
      summary: Get a single Credential
      operationId: credentialGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './credential.yaml#/components/parameters/credentialId'
      responses:
        200:
          description: The details of the desired Credential
          content:
            application/json:
              schema:
                $ref: './credential.yaml#/components/schemas/credential'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    put:
      tags:
        - Credential
      summary: Update a single Credential
      operationId: credentialUpdate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './credential.yaml#/components/parameters/credentialId'
      requestBody:
        description: An object containing the new properties for the Credential to update
        content:
          application/json:
            schema:
              $ref: './credential.yaml#/components/schemas/credential'
        required: true
      responses:
        200:
          description: The details of the updated Credential
          content:
            application/json:
              schema:
                $ref: './credential.yaml#/components/schemas/credential'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - Credential
      summary: Delete a single Credential
      operationId: credentialDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './credential.yaml#/components/parameters/credentialId'
      responses:
        200:
          description: The Credential has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
