openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Credential
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/user/credentials/{credentialId}/_reset:
    post:
      tags:
        - User Credentials
      summary: Reset the password of a Credential
      operationId: credentialPasswordReset
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../credential/credential.yaml#/components/parameters/credentialId'
      requestBody:
        description: The new password
        content:
          application/json:
            schema:
              $ref: './userCredentials.yaml#/components/schemas/passwordResetRequest'
        required: true
      responses:
        204:
          description: The updated Credential
          content:
            application/json:
              schema:
                $ref: '../credential/credential.yaml#/components/schemas/credential'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
