openapi: 3.0.2

info:
  title: Everyware Cloud REST API - User Credentials
  version: '1.0'
  contact:
    name: Eurotech
    url: https://www.eurotech.com

paths: {}

components:
  schemas:
    passwordChangeRequest:
      allOf:
        - description: Represent a request for changing the user password
          type: object
          properties:
            currentPassword:
              type: string
            newPassword:
              type: string
          example:
            currentPassword: "Welcome1234!"
            newPassword: "NewWelcome1234!"