openapi: 3.0.2

info:
  title: Everyware Cloud REST API - User Credentials
  version: '1.0'
  contact:
    name: Eurotech
    url: https://www.eurotech.com

paths:

  /{scopeId}/user/credentials/password:
    post:
      tags:
        - User Credentials
      summary: Change the user password
      operationId: passwordChangeRequest
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/passwordChangeRequest'
      responses:
        200:
          description: The details of the updated Credential
          content:
            application/json:
              schema:
                $ref: '../credential/credential.yaml#/components/schemas/credential'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
      description: Change logged user password