#!/bin/sh
################################################################################
#    Copyright (c) 2021, 2022 Eurotech and/or its affiliates and others
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
#    Contributors:
#        Eurotech
################################################################################

YOURKIT_AGENT="-agentpath:/usr/local/YourKit-JavaProfiler-2023.9/bin/linux-arm-64/libyjpagent.so=port=10001,listen=all"

java ${YOURKIT_AGENT} ${JAVA_OPTS} ${DEBUG_OPTS} ${JMX_OPTS} -jar kapua-service-authentication-2.1.0-SNAPSHOT-app.jar
