#!/bin/sh

################################################################################
#    Copyright (c) 2017 Red Hat Inc
#   
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#   
#    Contributors:
#        Red Hat Inc - initial API and implementation
################################################################################

# Check for keycloak integration

if [ -n "$KEYCLOAK_URL" -a -n "$KAPUA_URL" ]; then
   echo "Activating Keycloak integration"
   echo "  Keycloak: $KEYCLOAK_URL"
   echo "  Kapua: $KAPUA_URL"
   
   : KEYCLOAK_REALM=${KEYCLOAK_REALM:=kapua}
   : KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:=console}
   
   JAVA_OPTS="$JAVA_OPTS -Dsso.enabled=true"
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.client.id=${KEYCLOAK_CLIENT_ID}"
   
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.server.endpoint.auth=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth"
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.server.endpoint.token=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token"
   
   JAVA_OPTS="$JAVA_OPTS -Dsite.home.uri=${KAPUA_URL}"
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.redirect.uri=${KAPUA_URL}/sso/callback"
   
   export JAVA_OPTS
fi

# Continue with startup

exec /home/kapua/run-jetty "$@"
