#!/bin/sh

################################################################################
#    Copyright (c) 2017 Red Hat Inc
#   
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#   
#    Contributors:
#        Red Hat Inc - initial API and implementation
################################################################################

# Check for keycloak integration

if [ -n "$KEYCLOAK_SERVICE_HOST" -a -n "$KEYCLOAK_URI" ]; then
   echo "Activating Keycloak integration"
   
   JAVA_OPTS="$JAVA_OPTS -Dsso.enabled=true"
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.client.id=kapua"
   
   JAVA_OPTS="$JAVA_OPTS -Dsite.home.uri="
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.server.endpoint.auth=http://${KEYCLOAK_SERVICE_HOST}:${KEYCLOAK_SERVICE_PORT_HTTP}/auth/realms/master/protocol/openid-connect/auth"
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.server.endpoint.token=http://${KEYCLOAK_SERVICE_HOST}:${KEYCLOAK_SERVICE_PORT_HTTP}/auth/realms/master/protocol/openid-connect/token"
   JAVA_OPTS="$JAVA_OPTS -Dsso.openid.redirect.uri="
   
   export JAVA_OPTS
fi



exec /home/kapua/run-console "$@"
