#!/bin/sh
################################################################################
#    Copyright (c) 2011, 2018 Eurotech and/or its affiliates and others
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
#    Contributors:
#        Eurotech
################################################################################

java -jar \
-Dcommons.db.schema.update=true \
-Dcommons.db.connection.host=${SQL_DB_ADDR} \
-Dcommons.db.connection.port=${SQL_DB_PORT} \
-Dbroker.host=${BROKER_ADDR} \
-Dbroker.port=${BROKER_PORT} \
-Dkapua.lifecycleProcessor.messageSource.hono.host=${HONO_ADDR} \
-Dkapua.lifecycleProcessor.messageSource.hono.truststoreFile=${HONO_TRUSTSTORE_FILE} \
-Dcommons.eventbus.url="${SERVICE_BROKER_ADDR}" \
kapua-processor-lifecycle-hono-1.1.0-SNAPSHOT-uber.jar
java ${JAVA_OPTS} -jar kapua-processor-lifecycle-hono-1.1.0-SNAPSHOT-uber.jar
