name: 'Execute tests tagged in a certain way'
description: 'Execute tests suite for tests tagged as specified'
inputs:
  tag:
    description: Cucumber tag of the tests to run
    required: true
  needs-docker-images:
    description: true if this suite needs docker images, false otherwise
    required: false
    default: 'true'
#outputs:
runs:
  using: "composite"
  steps:
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
    - name: Cache Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
    - name: Docker images creation
      if: ${{ inputs.needs-docker-images == 'true' }}
      uses: ./.github/actions/cacheDockerRetry
      with:
        key: ${{ github.run_id }}-${{ github.run_number }}-docker-cache-{hash}  # cache is valid only for current run on the current repository
        restore-keys: |
          ${{ github.run_id }}-${{ github.run_number }}-docker-cache-
    - name: Dns look-up containers needed for tests - message-broker
      if: ${{ inputs.needs-docker-images == 'true' }}
      run: echo "127.0.0.1       message-broker" | sudo tee -a /etc/hosts
      shell: bash
    - name: Dns look-up containers needed for tests - job-engine
      if: ${{ inputs.needs-docker-images == 'true' }}
      run: echo "127.0.0.1       job-engine" | sudo tee -a /etc/hosts
      shell: bash
    - name: Test execution step
      run: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.filter.tags="${{ inputs.tag }}" -pl ${TEST_PROJECTS} verify
      shell: bash
    - name: Code-coverage results
      run: bash <(curl -s https://codecov.io/bash)
      shell: bash