name: 'Execute tests tagged in a certain way'
description: 'Execute tests suite for tests tagged as specified'
inputs:
  tag:
    description: Cucumber tag of the tests to run
    required: true
  needs-docker-images:
    description: true if this suite needs docker images, false otherwise
    required: false
    default: 'true'
#outputs:
runs:
  using: "composite"
  steps:
    - name: Clones Kapua repo inside the runner
      uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
        cache: 'maven' #TODO
    - name: Cache Maven repository #TODO
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Docker images creation
      if: ${{ inputs.needs-docker-images }}
      run: mvn -B ${BUILD_OPTS} -Pdocker -DskipTests clean install
      shell: bash
    - name: Dns look-up containers needed for tests - message-broker
      if: ${{ inputs.needs-docker-images }}
      run: echo "127.0.0.1       message-broker" | sudo tee -a /etc/hosts
      shell: bash
    - name: Dns look-up containers needed for tests - job-engine
      if: ${{ inputs.needs-docker-images }}
      run: echo "127.0.0.1       job-engine" | sudo tee -a /etc/hosts
      shell: bash
    - name: Test execution step
      uses: nick-fields/retry@v2.8.1
      with:
        timeout_minutes: 45
        retry_on: error
        max_attempts: 1
        command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.filter.tags=${{ inputs.tag }} verify
    - name: Code-coverage results
      run: bash <(curl -s https://codecov.io/bash)
      shell: bash