#!/bin/sh

################################################################################
#    Copyright (c) 2017 Red Hat Inc
#   
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#   
#    Contributors:
#        Red Hat Inc - initial API and implementation
################################################################################

START_ARGS="$START_ARGS -Djetty.home=/home/kapua/jetty"
START_ARGS="$START_ARGS -Djetty.base=/var/lib/jetty"

# START_ARGS : Arguments to the starter JVM
# JAVA_OPTS : Arguments to the server JVMs

eval echo "START_ARGS = $START_ARGS"
eval echo "JAVA_OPTS = $JAVA_OPTS"
eval exec /usr/bin/java $START_ARGS -jar /home/kapua/jetty/start.jar $JAVA_OPTS "$@"
